---
- hosts: localhost
  gather_facts: no
  environment:
    PYTHONWARNINGS: "ignore"
    REQUESTS_CA_BUNDLE: ""
    PYTHONHTTPSVERIFY: "0"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Run a File System Backup for subclient 'user_subclient' of backupset 'user_backupset'
      commvault.ansible.file_servers.backup:
        webserver_hostname: "10.31.70.66"
        client: "{{ client_name }}"
        agent_type: "File System"
        backupset: "defaultBackupSet"
        backup_level: "{{ backup_type }}"
        subclient: "default"
        commcell_username: "aman"
        commcell_password: "C@mmV@ult#07072024"
